### ISSUE TITLE
inotify_simple dependency

### ISSUE THREAD

**Issue by chapmanjacobd** [bugsink/snappea#1]
> the model of "just writing some unique file" is very simple to understand. And the division of labor regarding these files is also simple (the clients just put files there, the snappeaserver just cleans)
> https://github.com/bugsink/bugsink/blob/main/DESIGN-process-model.md

I feel like this is unnecessary complexity? It makes me wonder what the minimum latency is for the notify API and I wonder if sleeping for that number of `ms` would be mostly equivalent for an active system. But I'm not an inotify expert!

It's worth noting that there is a lightweight `LISTEN/NOTIFY` in SQLite:

- https://www.sqlite.org/c3ref/update_hook.html
- https://stackoverflow.com/questions/16872700/sqlite-data-change-notification-callbacks-in-python-or-bash-or-cli/16920926

Its use in Python requires ctypes but so does [inotify_simple](https://github.com/chrisjbillington/inotify_simple/blob/master/inotify_simple.py)

**Comment by vanschelven** [comment]
Probably "guilty as charged", that is, I'm not 100% convinced this amount of complexity is necessary myself.

I've even written down some [concrete ways forward](https://www.bugsink.com/blog/snappea-design/#considerations). Wasn't aware yet of the 2 concrete suggestions you're making here.

The real answer is "this will happen when there's enough pain". Are you experiencing any concrete pain already?

**Comment by chapmanjacobd** [comment]
> Are you experiencing any concrete pain already?

Well no, I'm just 1st-circle-of-Dante's-Inferno avoiding-job-search pretend-programming

I don't even use Django :/ didn't realize this is Django only
